import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import {Providers} from "@/app/providers";
import MainNavbar from "@/app/components/MainNavbar";
import {FooterSection} from "@/app/components/FooterSection";
import {ProfileAndNotificationTeacher} from "@/app/main/teacher/profileAndNotificationTeacher";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>

            <Providers>
                <MainNavbar/>
                <div className="min-h-screen" id="root">{children}</div>
                <ProfileAndNotificationTeacher/>
                <FooterSection/>
            </Providers>

        </>
    );
}
